### ISSUE TITLE
Custom DNS Resolver List

### ISSUE THREAD

**Issue by lappsec** [blacklanternsecurity/bbot#1041]
**Description**
It would be great to be able to provide a custom DNS resolver list for subdomain enumeration, especially when performing massdns scans. From what I can tell right now (I may be wrong) it uses the system resolvers, which could be a real bottleneck and comes with the possibility of being blocked for too many requests. 

In the past I think bbot used a large list of verified DNS resolvers, but that no longer appears to be the case. I apologize if this is already implemented and I just missed it.

**Comment by TheTechromancer** [comment]
Massdns uses this resolver list:

https://github.com/blacklanternsecurity/public-dns-servers

**Comment by lappsec** [comment]
Ok, well that makes more sense - thanks for clearing that up. Is it only the other tools that use the system resolvers?

On one host where I ran bbot I got a warning at the beginning that my system only had one resolver. Then on another system I was getting errors that DNS resolution was failing. I figured it was due to overloading the system resolver(s), but that may not be the case.

**Comment by TheTechromancer** [comment]
Yes, everything else in BBOT uses the system resolvers. This does result in a lot of DNS queries. Each hostname needs to be resolved to every record type (MX, NS, A, AAAA, etc.), and also checked for wildcards. 

We've considered allowing custom resolvers, but so far we've held off on it because it would be hard to enforce across all the modules and tools, and would introduce inconsistency between them. Right now the best solution is just to set whatever DNS servers you want in your OS.

**Comment by amiremami** [comment]
I have same issue
![dns](https://github.com/blacklanternsecurity/bbot/assets/15929497/b2a560aa-8306-4086-89a0-9bbea1a88f34)

So, I checked my `/etc/resolv.conf` and there was only 127.0.0.53 on my scaleway server. Now should I copy and paste these there?

https://github.com/blacklanternsecurity/public-dns-servers/blob/master/nameservers.txt

Or do I need to do anything or check something before?

Thanks 🙏
