### ISSUE TITLE
BBOT Config - Nuclei Default Mode 

### ISSUE THREAD

**Issue by Hax0rG1rl** [blacklanternsecurity/bbot#141]
Hi, 

This is not related to a bug, mostly a quick question. BBOT default config has nuclei configured mode as "**severe**", meaning that it scans only for high and critical. 

What're the other options here for someone who wants to do a full-fledged nuclei scan?  

Thanks!

**Comment by liquidsec** [comment]
Hi,

So we were actually talking about doing a blog post to explain this in a lot more detail, but basically:

**Severe**: High and Critical severity only 
**Manual**: Default settings, so every template (except w/ the intrusive tag). Many of the standard nuclei settings can be customized and will be passed through to nuclei.
**Technology**: This is basically just running nuclei's -as (-automatic-scan) mode. So it will use wappalyzer signatures to detect technologies and only run matching templates
**Budget**: This one is a little hard to explain briefly, but it's basically when you need your scan to be really lean but still want to benefit from the many templates that can be covered with only a couple extra requests. This is made possible by the way nuclei collapses templates that have the same request URL down. So with only 1 request, you can get over 400 nuclei templates. Basically this mode will scan through all the templates and calculate what templates it can use while still adhering to your request limit.

We chose "severe" mode as a default because its a good balance between having a leaner scan (critical and high templates are roughly 1/6th of all templates) and not missing any really important ones.

So to answer your question more directly, if you want all the templates just switch to manual mode. You can do this on the command line without changing your config like this:

`-c modules.nuclei.mode=manual`

Note that we always remove templates with the `intrusive` tag, unless you explicitly allow this in your config.

Cheers!

**Comment by liquidsec** [comment]
Closing due to lack of further activity after 10 days

**Comment by liquidsec** [comment]
Just leaving a note here for anyone finding this in the future, we've just changed the default mode so now MANUAL mode is default instead of severe
