### ISSUE TITLE
Error in dns.resolver module

### ISSUE THREAD

**Issue by Hax0rG1rl** [blacklanternsecurity/bbot#172]
**Describe the bug**

```[ERRR] bbot.scanner.manager: Error in ScanManager._emit_event(): module 'dns.resolver' has no attribute 'LifetimeTimeout'```

I also found this reported by some Asian guys, that seems to be related at some degree: 

https://github.com/lijiejie/subDomainsBrute/issues/67

**Expected behavior**
No error message. Subdomain enumeration magic start to happen. 

**BBOT Installation Method + Version**

Installation method: pip

**BBOT Command**
bbot -t t1.lst -f subdomain-enum --name t1_scan --output-dir t1_scan

**BBOT Config**
![image](https://user-images.githubusercontent.com/3704868/201211646-2c40987f-7e95-47f6-9ee9-1255697b5cd5.png)

**Logs**
If possible, please produce the bug while `--debug` is enabled, and attach the relevant parts of `~/.bbot/logs/bbot.debug.log`

**Screenshots**
![image](https://user-images.githubusercontent.com/3704868/201211568-65d90698-5336-4f62-8332-48820de75f82.png)

**Comment by TheTechromancer** [comment]
Thanks for reporting this. I've run into it myself occasionally, and I think it's because of a conflict with another Python library on your system.

The attribute does exist as shown here:
https://github.com/rthalley/dnspython/blob/master/dns/resolver.py#L159

Can you try uninstalling BBOT (`pip uninstall bbot`) and installing with pipx instead? This will ensure it gets installed in its own isolated Python environment.
```bash
# install pipx
python3 -m pip install --user pipx
# add pipx to your path
python3 -m pipx ensurepath
# reboot
reboot
# install bbot
python3 -m pipx install bbot
# run bbot
bbot --help
```

Let me know if that helps

**Comment by Hax0rG1rl** [comment]
Ok. Thank you. I will try that and provide an update. :)

**Comment by Hax0rG1rl** [comment]
Right. This seems to be fixed now. Thank you!
