### ISSUE TITLE
DNS Queries Are Failing

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [blacklanternsecurity/bbot#1730]
I get this constantly at the end of the scan on my server, what should I do to fix this?

![image](https://github.com/user-attachments/assets/1aa328a9-280f-425b-91f5-dfd0f5471868)

🙏

**Comment by TheTechromancer** [comment]
Most likely your DNS server is in the list of servers that massdns is using, so because of massdns you're being rate limited.

Decreasing `dns.brute_threads` would probably help.

On the dev side there are also a couple things we could do, like making sure your system's DNS servers are excluded from the  [nameservers wordlist](https://github.com/blacklanternsecurity/bbot/blob/b169b140df5db8040d3c8f33bcb183bf770ff42e/bbot/core/helpers/dns/brute.py#L19). 

Also, making that wordlist configurable.

Since I'm already working on DNS stuff, I'll see what I can do.

**Comment by TheTechromancer** [comment]
https://github.com/blacklanternsecurity/public-dns-servers/issues/1

**Comment by TheTechromancer** [comment]
https://github.com/blacklanternsecurity/bbot/pull/1723/commits/dd70fa10355f46b3188a1dac88f97b4e7f46bd34

**Comment by TheTechromancer** [comment]
Fixes have been pushed to https://github.com/blacklanternsecurity/bbot/pull/1723.

This PR automatically removes your system's DNS servers from the resolver list used by massdns. It also lets you use a custom resolver list via `dns.brute_nameservers`.
