### ISSUE TITLE
Replace FFUF with WFUZZ

### ISSUE THREAD

**Issue by liquidsec** [blacklanternsecurity/bbot#436]
We have witnessed some suspicious gremlins in FFUF. WFUZZ is written in Python, has better tests, and is overall more mature.

**Comment by TheTechromancer** [comment]
WFUZZ installation fails on most systems. This happens because WFUZZ depends on PycURL, which uses C extensions but does not provide wheels. PycURL does have Github workflows for building wheels, but they have fallen into disrepair.

There is an upstream issue for this:
https://github.com/pycurl/pycurl/issues/738

**Comment by liquidsec** [comment]
Closing indefinitely unless compelled to revisit. Without proper maintenance to WFUZZ and it's downstream libraries this is a no-go.
