### ISSUE TITLE
IP_ADDRESS missing from human output

### ISSUE THREAD

**Issue by AkikoOrenji** [blacklanternsecurity/bbot#679]
**Describe the bug**
IP_ADDRESS missing from human output but is show in CSV and JSON

**Expected behavior**
I think the outputs should all be the same unless there's a specific reason IP_ADDRESS are dropped from human readable output. 

**BBOT Command**
Example: `bbot -t evilcorp.net -n evilcorp.net  -f passive`

**OS, BBOT Installation Method + Version**
Example: `OS: Ubuntu Linux, Installation method: pipx, BBOT version: v1.1.0.2124  Python 3.9.5`

**BBOT Config**

Out of the box

**Comment by TheTechromancer** [comment]
By default, BBOT only displays in-scope assets. Unless you specify the parent IP range as a target, the IP addresses will not show.

However, it is possible to change this behavior with the `scope_report_distance` config option. To display everything out to a scope distance of 1 (the default is 0, meaning in-scope only), you can run BBOT like this:

```bash
bbot -t evilcorp.com -c scope_report_distance=1
```

EDIT: On further inspection, I can see there is some inconsistency. You're right, the results of these different outputs should be the same. The difference in the "human" output was due to some unintended interaction between the duplicate event detection and the forced output of certain events. (Certain IP_ADDRESS events will always be shown if they led to an in-scope discovery, e.g. if they have a PTR record, even if they are out of scope. The purpose of this is to ensure a full chain of events can always be constructed, i.e. to prevent orphaned nodes in the graph).

Anyway, suffice to say thanks for finding this bug! It is fixed in this commit: 1f36524c1f51dd689149253878ade4d46d9d6357
